version: "3.3"

services: 
    web:
        build: .
        ports: 
            - 8000:8000
        environment: 
            LOCAL: "true"
            PORT: 8000
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
